[tool.poetry]
name = "biliapi"
version = "0.1.0"
description = ""
authors = ["SK-415 <2967923486@qq.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
httpx = "^0.18.2"

[tool.poetry.dev-dependencies]
black = "^21.7b0"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
