[tool.poetry]
name = "bilireq"
version = "0.1.0"
description = ""
authors = ["SK-415 <2967923486@qq.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
httpx = "^0.18.2"
qrcode = {extras = ["pil"], version = "^7.1", optional = true}
rsa = "^4.7.2"

[tool.poetry.dev-dependencies]
black = "^21.7b0"

[tool.poetry.extras]
qrcode = ["qrcode"]

# [[tool.poetry.source]]
# name = "tsinghua"
# url = "https://pypi.tuna.tsinghua.edu.cn/simple/"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
